### ISSUE TITLE
Do customer.h

### ISSUE THREAD

**Issue by Prashanthkoder** [Prashanthkoder/TaxiManager#4]
Customer.h is to be done. I t should have the class customer for now 
@skannorv3

**Comment by skannorv3** [comment]
I want manager.h

**Comment by Prashanthkoder** [comment]
> I want manager.h

Ok

**Comment by Prashanthkoder** [comment]
> I want manager.h

Ok

> I want manager.h

If u want u can deassign urself from this

**Comment by skannorv3** [comment]
Deassign is an option on the computer or a human option?😛

**Comment by skannorv3** [comment]
You liked your own comment 😂

**Comment by Prashanthkoder** [comment]
> Deassign is an option on the computer or a human option?

On computer

**Comment by Prashanthkoder** [comment]
> You liked your own comment

Dont spam here

**Comment by Prashanthkoder** [comment]
> Deassign is an option on the computer or a human option?

Leave it i de assigned u
